version: "3"

services:
  web:
    build:
      context: .
      args:
        - BUILD_ENV=development
      dockerfile: Dockerfile
    command: |
        /bin/bash -c '/bin/sleep infinity;'
    ports:
      - "8000:8000"
    volumes:
      - .:/app
