version: 2.1

orbs:
  win: circleci/windows@1.0.0

defaults: &defaults
  docker:
    - image: circleci/python:3.7-browsers
  environment:
    - BROWSER: headlesschrome
  working_directory: ~/repo

jobs:
  test_windows:
    executor: win/vs2019
    steps:
      - checkout
      - run:
          name: Do Nothing
          command: |
            true

  lint:
    <<: *defaults
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: Do Nothing
          command: |
            true

  test_py36:
    <<: *defaults
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run:
          name: Do Nothing
          command: |
            true

  test_py37:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Do Nothing
          command: |
            true

  test_py38:
    <<: *defaults
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Do Nothing
          command: |
            true

  test_robot:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install Python dependencies
          command: |
            virtualenv venv
            venv/bin/pip install -r requirements_dev.txt
      - run:
          name: Install sfdx
          command: |
            mkdir sfdx
            wget -qO- https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz | tar xJ -C sfdx --strip-components 1
            ./sfdx/install
      - run:
          name: Create scratch org
          command: |
            echo $SFDX_HUB_KEY_BASE64 | base64 --decode > sfdx.key
            sfdx force:auth:jwt:grant --clientid $SFDX_CLIENT_ID --jwtkeyfile sfdx.key --username $SFDX_HUB_USERNAME --setdefaultdevhubusername -a hub
            venv/bin/cci org info prerelease > org_info.txt
            venv/bin/cci org default prerelease
      - run:
          name: Run robot tests
          command: |
            mkdir -p robot_results/robot
            # we need to modify our task to make it easier to save the
            # output.xml file with a unique name. Until then, we have
            # to manually preserve each file under a different name
            venv/bin/coverage run --append venv/bin/cci task run robot -o name "CumulusCI" -o suites cumulusci/robotframework/perftests  -o xunit robot_results/robot/perftests.xml || true
            mv output.xml robot_results/robot/perftests-output.xml
            mv selenium-screenshot-* robot_results/robot || true
      - run:
          name: Consolidate robot outputs into a single report and log
          when: always
          command: |
            venv/bin/rebot --outputdir robot_results/robot  robot_results/robot/*-output.xml
      - run:
          name: Delete scratch org
          command: |
            venv/bin/cci org scratch_delete prerelease
          when: always
      - run:
          name: Preserve coverage
          command: |
            mv .coverage .coverage.robot
          when: always
      - store_test_results:
          path: robot_results
      - store_artifacts:
          path: robot_results/
          destination: robot
      - persist_to_workspace:
          root: .
          paths:
            - .coverage.robot

  test_release:
    <<: *defaults
    environment:
      CUMULUSCI_KEYCHAIN_CLASS: cumulusci.core.keychain.EnvironmentProjectKeychain
    steps:
      - checkout
      - run:
          name: Do Nothing
          command: |
            true



  report:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Report coverage
          command: |
            virtualenv venv
            venv/bin/pip install coverage coveralls
            venv/bin/coverage combine .coverage.*
            venv/bin/coverage report -m
            venv/bin/coveralls

workflows:
  version: 2
  build_test_report:
    jobs:
      - lint:
          filters:
            branches:
              ignore:
                - /dependabot\/.*/
      - test_py36:
          filters:
            branches:
              ignore:
                - /dependabot\/.*/
      - test_py37:
          filters:
            branches:
              ignore:
                - /dependabot\/.*/
      - test_py38:
          filters:
            branches:
              ignore:
                - /dependabot\/.*/
      - test_robot:
          filters:
            branches:
              ignore:
                - /dependabot\/.*/
      - test_release:
          filters:
            branches:
              ignore:
                - /dependabot\/.*/
      - test_windows:
          filters:
            branches:
              only:
                - master
                - /.*windows.*/
      - report:
          requires:
            - test_py36
            - test_py37
            - test_py38
            - test_robot
            - test_release
