name: Build docs

on:
  push:
    paths:
    - 'docs/**'

jobs:
  lint:
    name: Build docs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: pip cache
      uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements*.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install dependencies
      run: |
        python -m pip install -U pip
        pip install -r requirements_dev.txt
    - name: Make docs
      run: make docs
    - name: Upload docs
      uses: actions/upload-artifact@v2
      with:
        name: docs
        path: docs/_build/html
