name: Feature Test

on:
  schedule:
    - cron:  '13 13 * * *'
  workflow_dispatch:
    inputs:
      tags:
        description: 'Test scenario tags'  
  push:
    branches:
    - feature/run-integration-tests-daily

env:
  CUMULUSCI_KEY: ${{ secrets.CUMULUSCI_KEY }}

jobs:
  integration_tests:
    name: "Integrations tests: Python 3.8"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: pip cache
      uses: actions/cache@v1
      with:
        path: ~\AppData\Local\pip\Cache
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements*.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install Python dependencies
      run: |
        python -m pip install -U pip
        pip install -r requirements_dev.txt
    - name: Install sfdx
      run: |
        mkdir sfdx
        wget -qO- https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz | tar xJ -C sfdx --strip-components 1
        ./sfdx/install
        echo $SFDX_HUB_KEY_BASE64 | base64 --decode > sfdx.key
        sfdx force:auth:jwt:grant --clientid $SFDX_CLIENT_ID --jwtkeyfile sfdx.key --username $SFDX_HUB_USERNAME --setdefaultdevhubusername -a hub
      env:
        SFDX_HUB_KEY_BASE64: ${{ secrets.SFDX_HUB_KEY_BASE64 }}
        SFDX_CLIENT_ID: ${{ secrets.SFDX_CLIENT_ID }}
        SFDX_HUB_USERNAME: ${{ secrets.SFDX_HUB_USERNAME }}
    - name: Run integration tests
      run: |
        coverage run --append $(which pytest) --org dev
    - name: Delete scratch org
      if: always()
      run: |
        cci org scratch_delete dev
